package redfishreceiver

import "go.opentelemetry.io/collector/pdata/pcommon"

func (s *redfishScraper) scrapeComputerSystem(ts pcommon.Timestamp, baseUrl string, compSys *ComputerSystem) {
	s.mb.RecordSystemPowerstateDataPoint(ts,
		powerStateToMetric(compSys.PowerState),
		baseUrl,
		compSys.Id,
		compSys.AssetTag,
		compSys.BiosVersion,
		compSys.HostName,
		compSys.Model,
		compSys.Name,
		compSys.Manufacturer,
		compSys.SerialNumber,
		compSys.SKU,
		compSys.SystemType,
	)
	s.mb.RecordSystemStatusHealthDataPoint(
		ts,
		statusHealthToMetric(compSys.Status.Health),
		baseUrl,
		compSys.Id,
		compSys.AssetTag,
		compSys.BiosVersion,
		compSys.HostName,
		compSys.Model,
		compSys.Name,
		compSys.Manufacturer,
		compSys.SerialNumber,
		compSys.SKU,
		compSys.SystemType,
	)
	s.mb.RecordSystemStatusStateDataPoint(
		ts,
		statusStateToMetric(compSys.Status.State),
		baseUrl,
		compSys.Id,
		compSys.AssetTag,
		compSys.BiosVersion,
		compSys.HostName,
		compSys.Model,
		compSys.Name,
		compSys.Manufacturer,
		compSys.SerialNumber,
		compSys.SKU,
		compSys.SystemType,
	)
}

func (s *redfishScraper) scrapeChassis(ts pcommon.Timestamp, hostName, baseUrl string, chassis *Chassis) {
	s.mb.RecordChassisPowerstateDataPoint(
		ts,
		powerStateToMetric(chassis.PowerState),
		hostName,
		baseUrl,
		chassis.Id,
		chassis.AssetTag,
		chassis.Model,
		chassis.Name,
		chassis.Manufacturer,
		chassis.SerialNumber,
		chassis.SKU,
		chassis.ChassisType,
	)
	s.mb.RecordChassisStatusHealthDataPoint(
		ts,
		statusHealthToMetric(chassis.Status.Health),
		hostName,
		baseUrl,
		chassis.Id,
		chassis.AssetTag,
		chassis.Model,
		chassis.Name,
		chassis.Manufacturer,
		chassis.SerialNumber,
		chassis.SKU,
		chassis.ChassisType,
	)
	s.mb.RecordChassisStatusStateDataPoint(
		ts,
		statusStateToMetric(chassis.Status.State),
		hostName,
		baseUrl,
		chassis.Id,
		chassis.AssetTag,
		chassis.Model,
		chassis.Name,
		chassis.Manufacturer,
		chassis.SerialNumber,
		chassis.SKU,
		chassis.ChassisType,
	)
}

func (s *redfishScraper) scrapeFans(ts pcommon.Timestamp, hostName, baseUrl, chassisId string, fans []Fan) {
	for _, fan := range fans {
		s.mb.RecordFanReadingDataPoint(
			ts,
			*fan.Reading,
			hostName,
			baseUrl,
			chassisId,
			fan.Name,
		)
		s.mb.RecordFanStatusHealthDataPoint(
			ts,
			statusHealthToMetric(fan.Status.Health),
			hostName,
			baseUrl,
			chassisId,
			fan.Name,
		)
		s.mb.RecordFanStatusStateDataPoint(
			ts,
			statusStateToMetric(fan.Status.State),
			hostName,
			baseUrl,
			chassisId,
			fan.Name,
		)
	}
}

func (s *redfishScraper) scrapeTemperatures(ts pcommon.Timestamp, hostName, baseUrl, chassisId string, temps []Temperature) {
	for _, temp := range temps {
		s.mb.RecordTemperatureReadingDataPoint(
			ts,
			int64(*temp.ReadingCelsius),
			hostName,
			baseUrl,
			chassisId,
			temp.Name,
		)
		s.mb.RecordTemperatureStatusHealthDataPoint(
			ts,
			statusHealthToMetric(temp.Status.Health),
			hostName,
			baseUrl,
			chassisId,
			temp.Name,
		)
		s.mb.RecordTemperatureStatusStateDataPoint(
			ts,
			statusStateToMetric(temp.Status.State),
			hostName,
			baseUrl,
			chassisId,
			temp.Name,
		)
	}
}
